stages:
- stage: deploy
  jobs:
  - deployment: DeployAKS
    displayName: deploy AKS Cluster Mock
    pool:
      vmImage: 'Ubuntu-latest'
    # creates an environment if it doesn't exist
    environment: 'Roll-Environment-dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo deploying AKS Cluster through Terraform